packadd minpac

call minpac#init({'verbose': 3})
call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
call minpac#add('altercation/vim-colors-solarized')

command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
command! PackStatus call minpac#status()

syntax on

let g:airline_powerline_fonts = 1
let g:airline_theme = 'solarized'

set background=dark
set tabstop=4
set softtabstop=4
set expandtab

set scroll=10

set number

filetype indent on 

set lazyredraw

set wildmenu

set showmatch

set incsearch

set hidden
"Para cambiar de buffer sin escribir cambios

inoremap kj <C-C> 

vnoremap kj <C-C>

cnoremap kj <C-C>
"makes escape more comfortable

let mapleader = ","

vnoremap <leader>y "+y
nnoremap <leader>p "+p
nnoremap <leader>o "*p
"yanks and pastes to and from the clipboard register

nnoremap <leader>ev :vsp ~/.vim/vimrc<cr>
"opens vimrc in a vertical split

nnoremap <leader>sv :so ~/.vim/vimrc<cr>
"sources vimrc so any saved changes have effect on the current buffer

noremap <leader>t :sh<cr>

nnoremap <leader>u viw~

noremap <leader>w <c-w><c-w>

nnoremap <leader>lc :! pdflatex --jobname=texaux %<cr>
"compile latex file to view it

nnoremap <leader>lw :! pdflatex %<cr>
"compile latex file with its source name

nnoremap <leader>lv :! zathura texaux.pdf & disown<cr>
"opens the compiled pdf latex file in zathura

nnoremap <leader>b :bnext<cr>
"Cambio rapido al siguiente buffer

inoremap <C-e> <C-C>"+pa
"Permite pegar contenido del registro + en insert mode
